import { Bitter, Montserrat } from "@next/font/google";
import Header from "./components/header/Header";
import "./globals.css";

export const metadata = {
  title: "TelcoPlus Next.js",
  description: "Generated by Dillonzellis using Next.js",
};

const mont = Montserrat({
  variable: "--mont-font",
  subsets: ["latin"],
});

const bitter = Bitter({
  variable: "--bitter-font",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${mont.variable} ${bitter.variable}`}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
