import { Crimson_Pro, Montserrat } from "next/font/google";
import Footer from "./components/footer/Footer";
import Header from "./components/header/Header";
import "./globals.css";

export const metadata = {
  title: "TelcoPlus Next.js",
  description: "Generated by Dillonzellis using Next.js",
};

const mont = Montserrat({
  variable: "--mont-font",
  subsets: ["latin"],
});

const crimson = Crimson_Pro({
  variable: "--crimson-font",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${mont.variable} ${crimson.variable}`}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
